### ISSUE TITLE
TypeError: 'dict_keys' in yahoofinancials/__init__.py line 470 for python 3.x

### ISSUE THREAD

**Issue by crendon8** [JECSand/yahoofinancials#1]
I followed the instructions from a similar issue found on stackoverflow: https://stackoverflow.com/questions/17322668/typeerror-dict-keys-object-does-not-support-indexing

and applied the same logic to line 470. I replaced:
date_key = re_data[self.ticker][0].keys()[0]

with: 
date_key = list(re_data[self.ticker][0])[0]

and works for me.
-Carlos

**Comment by JECSand** [comment]
Thanks for sharing that. I'll go ahead and make a minor fix for that.

**Comment by JECSand** [comment]
Issue Fixed with v0.5 release.
