### ISSUE TITLE
Error occurs in get_net_income() 

### ISSUE THREAD

**Issue by meteorologytoday** [JECSand/yahoofinancials#10]
This is the code (after delete unrelated lines) given in the "Single Ticker Example" of github frontpage.

### Code
```python3
from yahoofinancials import YahooFinancials

ticker = 'AAPL'
yahoo_financials = YahooFinancials(ticker)

apple_net_income = yahoo_financials.get_net_income()
```

### Output

> Traceback (most recent call last):
  File "test.py", line 6, in <module>
    apple_net_income = yahoo_financials.get_net_income()
  File "/export/home/tienyiah/miniconda3/lib/python3.6/site-packages/yahoofinancials/__init__.py", line 700, in get_net_income
    return self._financial_statement_data('income', 'incomeStatementHistory', 'netIncome', 'annual')
  File "/export/home/tienyiah/miniconda3/lib/python3.6/site-packages/yahoofinancials/__init__.py", line 587, in _financial_statement_data
    date_key = re_data[self.ticker][0].keys()[0]
TypeError: 'dict_keys' object does not support indexing

### Version information:
>Python 3.6.5 :: Anaconda, Inc.
yahoofinancials: v1.0

**Comment by JECSand** [comment]
Thank you for alerting me to this. I fixed this error and just released a 1.1 version containing the fix.

Thanks again and let me know if you come across anything else!
