### ISSUE TITLE
Financial History 

### ISSUE THREAD

**Issue by emamars95** [JECSand/yahoofinancials#104]
Dear, 
I want to add a comment on your yahoofinancials project. I add my comment here due to git hub does not support private messages anymore. 

Would you be interested in integrating, in addition to the yahoo financial statements, the statements provided by the U.S. Securities and Exchange Commission's (EDGAR) database? Instead of only 4 quarters or 4 years, you can find a much better-furnished database there. I was already writing a section of the code to pull the JSON file directly from the website there before noticing your project. 
Let me know if you are interested.

**Comment by JECSand** [comment]
@emamars95 I'm interested. My plate has been rather full lately, hence the late response. Feel free to reach me at sandersconnor1@gmail.com if you are still investigating this.
