### ISSUE TITLE
Can't read symbol listing from another library

### ISSUE THREAD

**Issue by Jabaker35** [JECSand/yahoofinancials#111]
Hello,

I am currently working on a class project and I had to download a few different versions of yahoo finance where I was able to get the complete symbol listings for Nasdaq, S&P500, and others. However, your update messed me up so now the historical data I need to get is no longer able to read the total symbol listings from one of the yahoo finance libraries I downloaded. It would be nice if this had a complete symbol listings without manually typing it in unless it is preferred. The name of the library I used for the complete symbol listing it yahoo_fin. Thanks for your help.

http://theautomatic.net/yahoo_fin-documentation/

**Comment by JECSand** [comment]
@Jabaker35 Unfortunately, v1.7 was necessary due to a breaking change on Yahoo Finance's end. Please refer to #105.
We use the symbols accepted by Yahoo Finance's API. If those have changed, it's on Yahoo Finance's end. Would you mind replying with some examples of these symbol changes?

**Comment by Jabaker35** [comment]
I don't have any examples. It is another open source library which has a whole listing of different symbols from different exchanges. I have already provided you the link so you can see for yourself. I have the code which creates the data frame between this and the other library if you would like to take a look at it.
