### ISSUE TITLE
Decrypt error

### ISSUE THREAD

**Issue by trexthemullaman** [JECSand/yahoofinancials#124]
Getting the following error:
    raise Exception("error decrypting Yahoo datastore with hardcoded keys")
Exception: error decrypting Yahoo datastore with hardcoded keys

**Comment by JECSand** [comment]
@trexthemullaman Let me look into this.

**Comment by paulhan93** [comment]
I too am getting this error

**Comment by JECSand** [comment]
Just committed a fix for this on the development branch, getting ready to push to PyPI.

**Comment by JECSand** [comment]
@trexthemullaman @paulhan93 v1.11 is now on PyPI, can confirm yahoofinancials is working again. Please upgrade and let me know if there's any further issues.
