### ISSUE TITLE
Issues 1) yahoofinancials get_stock_profile_data() KeyError: 'profile' AND 2) suggested Pandas dataframe output instead of dict for reformat=True of get_financial_stmts

### ISSUE THREAD

**Issue by SymbReprUnlim** [JECSand/yahoofinancials#127]
Python version 3.7
Debian Buster/Linux
yahoofinancials version 1.11 dated 1/26/2023

Console output:
Traceback (most recent call last):
  File "test_yahoofinancials.py", line 17, in <module>
    obj_profile_data=yfin_obj.get_stock_profile_data()
  File "/home/pi/.local/lib/python3.7/site-packages/yahoofinancials/yf.py", line 114, in get_stock_profile_data
    self.get_stock_data(statement_type='profile', tech_type='', report_name='assetProfile'), 'earnings')
  File "/home/pi/.local/lib/python3.7/site-packages/yahoofinancials/etl.py", line 651, in get_stock_data
    dict_ent = self._create_dict_ent(self.ticker, statement_type, tech_type, report_name, hist_obj)
  File "/home/pi/.local/lib/python3.7/site-packages/yahoofinancials/etl.py", line 573, in _create_dict_ent
    YAHOO_URL = self._BASE_YAHOO_URL + up_ticker + '/' + self.YAHOO_FINANCIAL_TYPES[statement_type][0] + '?p=' + \
KeyError: 'profile'

------------------
(program exited with code: 1)

Python code relevant extracts:
from yahoofinancials import YahooFinancials as yfin
ticker="MSFT"
yfin_obj=yfin(ticker)
obj_is=yfin_obj.get_financial_stmts("quarterly","income",reformat=True)   # reformat==False returns very large raw dictionary; True returns dict len=1 ??? NOT a Pandas DataFrame (which was hoped for)
obj_profile_data=yfin_obj.get_stock_profile_data()           # THIS python code is causing the KeyError: 'profile' to appear; Documentation on how to use relatively new get_stock_profile_data() routine ???

**Comment by JECSand** [comment]
@SymbReprUnlim Working on fixing this now. Also I'm open to having a pandas output option.

**Comment by JECSand** [comment]
@SymbReprUnlim v1.12 is now up on PyPI which includes a fix for this error. Thank you so much for bringing it to my attention. 

Also I added your Pandas suggestion to the v2 ideas discussion:
https://github.com/JECSand/yahoofinancials/discussions/118

Let me know if you have anything further issues.

**Comment by SymbReprUnlim** [comment]
Hi Connor, Rob here.  A quick note and thank you for:
1) Responding to the above issue, 2) Fixing the issue, 3) Being open-minded about suggested changes,
4) Taking time to move / add the suggested Pandas output for financial statements to the v2 ideas discussion and
5) showing/relaying a link to discussion issue #118!!

In today's multifaceted, frequently polarized and stressful programming, business, political and social environment: Open-mindedness and Flexibility remain successful keys to advancing technology, software, human development and businesses.

AVIS Budget Group Inc, the car sharing provider has the largest market share in their industry. Their business motto is "We Try Harder!"

Inspiration - How to Be Open-Minded  https://www.verywellmind.com/be-more-open-minded-4690673

Feel free to close this issue or I'll close it later.  The fix per v1.12 works from this end!  All the Best!
