### ISSUE TITLE
Too awesome to say thanks

### ISSUE THREAD

**Issue by hiroshi-c** [JECSand/yahoofinancials#13]
@JECSand How can I buy you a beer? This tool is so awesome!!

**Comment by JECSand** [comment]
@hiroshi-c Thank you so much for the compliment! I am very glad this module is proving to be useful for people! This project is 100% free, open source, and I do not accept donations (Do not want to give the impression that I am profiting in any form or fashion off providing easy access to Yahoo Data). However, if you are ever in the Dallas-Ft. Worth, TX area, feel free to drop a message and I'll take you up on that beer!

Thanks for using the module!
