### ISSUE TITLE
What is this odd request to "https://s.yimg.com/uc/finance/dd-site/js/main."?

### ISSUE THREAD

**Issue by RiverRo** [JECSand/yahoofinancials#131]
I'm looking at my logs and noticed ```DEBUG:urllib3.connectionpool:https://s.yimg.com:443 "GET /uc/finance/dd-site/js/main.e0c853d8cea2b75a5208.min.js HTTP/1.1" 200 None```.  I see that part of the URL is on line 168 in the etl.py code but I'm not sure what it does.  I'm a little surprised by this "non-yahoo" request.

**Comment by decodedcoder** [comment]
I was wondering the same thing a couple of days ago when I started using this module.
If you run nslookup, it shows that it's a yahoo  edge server:


'Non-authoritative answer:
s.yimg.com	canonical name = edge.gycpi.b.yahoodns.net.
Name:	edge.gycpi.b.yahoodns.net
Address: 69.147.82.60
Name:	edge.gycpi.b.yahoodns.net
Address: 69.147.82.61
'

Hope that helps.

**Comment by RiverRo** [comment]
@decodedcoder Thx for the explanation and a re-introduction to what was a forgotten tool for me. I see you opened #132 which was the problem that started my exploration into my logs.  Cheers.
