### ISSUE TITLE
Not able to receive data from the yahoo financials API

### ISSUE THREAD

**Issue by vaibhvbedi** [JECSand/yahoofinancials#134]
Hi,

My code is 

from yahoofinancials import YahooFinancials 
ticker = 'AAPL'
yahoo_financials = YahooFinancials(ticker)
balance_sheet_data_qt = yahoo_financials.get_financial_stmts('quarterly', 'balance')
print(balance_sheet_data_qt)

I am getting the none output
![image](https://user-images.githubusercontent.com/50806170/218326448-4d67108e-518b-43b7-80fe-99e42d6dbc42.png)

Please Let me know how I can solve this

**Comment by JECSand** [comment]
@vaibhvbedi Currently working on a refactor to address this. I will have a new version out tonight with a stable long term fix. Very close.

**Comment by JECSand** [comment]
Closing because issue is a duplicate of #132
