### ISSUE TITLE
Average Daily Volumes returning None

### ISSUE THREAD

**Issue by nblade66** [JECSand/yahoofinancials#137]
get_ten_day_avg_daily_volume() and get_three_month_avg_daily_volume() are both returning None

**Comment by JECSand** [comment]
@nblade66 Thank you for bringing this to my attention. I’ll review after work tonight. Could you share the tickers/Symbols you are attempting this with?

**Comment by nblade66** [comment]
VLDR, TSLA, XPEV
Those are the tickers I was testing the problem with (you can see what my mind has been on recently haha).

**Comment by JECSand** [comment]
@nblade66 Just released v1.14 which includes a fix for **get_ten_day_avg_daily_volume()**. Unfortunately the data for **get_three_month_avg_daily_volume()** seems to now be missing from Yahoo. I removed that method from the package for now. If we can locate the data, I'd be happy to add it back in.
