### ISSUE TITLE
who to contact if there is some missing data

### ISSUE THREAD

**Issue by climghub** [JECSand/yahoofinancials#16]
First of all I would like to thank you @JECSand for such a wonderful library. 

I have recently noticed that there are some missing data for my counters, and I tried to feedback to yahoo but I was told that yahoo finance API has been disabled (https://forums.yahoo.net/t5/Known-issues-and-updates/Yahoo-Finance-API-disabled/m-p/392760#M14)

From where actually these data are pulled from? Is there any channel to feedback about the missing data? It is quite a thorn for me at the moment.

**Comment by climghub** [comment]
I could see the same issue in the website historical data. So the issue is with Yahoo then. Sorry for troubling :) I think you can close the issue.

**Comment by JECSand** [comment]
Thanks for the question. 

Closing the issue.
