### ISSUE TITLE
Unable to get stock profile data

### ISSUE THREAD

**Issue by nathphoenix** [JECSand/yahoofinancials#160]
Please this function is failing **get_stock_profile_data** and others when i run them.

This is the error below

`HTTPSConnectionPool(host='query2.finance.yahoo.com', port=443): Max retries exceeded with url: /v6/finance/quoteSummary/googl?modules=assetProfile&formatted=False&lang=en-US&region=US&corsDomain=finance.yahoo.com (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A2BE011000>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')))`

`Server replied with server error code, HTTP 404 code while opening the url: https://query1.finance.yahoo.com/v6/finance/quoteSummary/googl?modules=assetProfile&formatted=False&lang=en-US&region=US&corsDomain=finance.yahoo.com`

@flipdazed @sylvandb @VKorelsky 

Please what could be the possible reason

**Comment by pzarfos** [comment]
Are you running an ad-blocker?

I am running pi-hole and had a similar issue, which I fixed by adding the yahoo finance domain names to my ad-blocker whitelist.

more info here - https://github.com/JECSand/yahoofinancials/issues/159#issuecomment-1807168165

**Comment by JECSand** [comment]
@GerdSidan Could you try that on v1.18?

**Comment by JECSand** [comment]
Just released v1.19 which includes a fix for this issue.
