### ISSUE TITLE
Error when running test script

### ISSUE THREAD

**Issue by micksulley** [JECSand/yahoofinancials#167]
I am getting errors with my code and so I ran the code in the overview in readme and that errors as well.  I am running on Ubuntu server 22.04.3 LTS and 
The output is attached
[err20231212.txt](https://github.com/JECSand/yahoofinancials/files/13647100/err20231212.txt)
Is it something I have done wrong?
Thanks
Mick

**Comment by JECSand** [comment]
@micksulley No, yahoo finance is making changes to their system. I'll try to get a solution going ASAP. My job has been extra busy, which is slowing me down however.

**Comment by JECSand** [comment]
Getting close to having a fix for this.

**Comment by JECSand** [comment]
Just released v1.19 which includes a fix for this issue.

**Comment by micksulley** [comment]
My code works again!
Thank you
Mick
