### ISSUE TITLE
Add Support for Key Statistics

### ISSUE THREAD

**Issue by joesixpack** [JECSand/yahoofinancials#18]
https://finance.yahoo.com/quote/AAPL/key-statistics?p=AAPL

**Comment by JECSand** [comment]
I'll take a look at this tonight to see if I can add this feature to the v1.4 release.

Thanks for the info!

**Comment by joesixpack** [comment]
Be aware there is some kind of pacing enforcement by Yahoo.  I believe the same limitations for the CSV history apply to web scraping, e.g. 2000 requests per hour.  I've only managed it successfully with 1 thread and a bit over a second between requests.  When you violate it, it will return a 404 error encoded in the url with a redirect to the home page.

**Comment by JECSand** [comment]
This feature has been added in v1.4! The method to get this data is called "get_key_statistics_data()".

Let me know if you have any issues and thank you for using YahooFinancials!

**Comment by DebugMeIfYouCan** [comment]
@joesixpack @JECSand hello, just wondering how you can get the `total Cash`, `total Debt` or `Levered Free Cash Flow` from the Key Statistics?

https://finance.yahoo.com/quote/AAPL/key-statistics?p=AAPL
