### ISSUE TITLE
Read the Json return from all_statement_data_qt =  yahoo_financials.get_financial_stmts

### ISSUE THREAD

**Issue by naveenkumarnair** [JECSand/yahoofinancials#2]
Wanted to check if you have already defined the module that reads the Json output from get_financial_stmts and segregates the data for Balance Sheet, Income Cashflow statements already?

**Comment by JECSand** [comment]
Hi Naveen!

I have not finished this feature yet. I have noted your feature request and have no problem adding it soon. 
I am in the middle of a big sprint right now for my day job. I could probably get to this myself within two weeks. 

Also if you want to become a contributer for the project, I'd love to bring you on (or anyone else qualified). That way you can get to this sooner than I could if needed and so we can build this out more. I'd love to get some more calculated measure methods added as well. 

Let me know and if so I can create a development guide for us to work by. 

Thanks!

**Comment by JECSand** [comment]
Closing issue. Release to address this feature request scheduled for May 17th, 2018 or sooner.
