### ISSUE TITLE
feature request to work around yahoo financials dropping dividends

### ISSUE THREAD

**Issue by nealeyoung** [JECSand/yahoofinancials#20]
There is a bug in the yahoo data server (not a bug in the yahoofinancials package here) that adversely affect peoples who use this package.  I'm not sure where else to document it, and I would like to request a feature for the package that will allow working around the bug.

The bug occurs when one asks for historical data in weekly, monthly, or larger periods.  For example, the VBILX fund has regular dividends each month, but if you ask for _monthly_ historical data for _more than a few years_ back, many recent dividends will not be reported.  You can see this at the web site e.g. at the following URL:

https://sg.finance.yahoo.com/quote/VBILX/history?period1=1264482000&period2=1548478800&interval=1mo&filter=history&frequency=1mo

Note that If you reduce the time period (e.g. to the last year), or you ask for _daily_ instead of monthly data, the server reports all recent dividends correctly.  Apparently, the bug is triggered when more than one dividend occurs within a given period (e.g. two in a month), in which case the yahoo server allocates some dividends to the wrong periods, resulting in recent ones being dropped.  (If you look into the data returned by the corresponding call to get_historical_stock_data of this package, you can see that the dividends reported are sometimes reported for the wrong periods, and some dividends are being lost.)

One workaround for those who want historical dividends is simply to request the _daily_ historical data.  But this can increase the downloaded data by a factor of 30 or so (since daily prices are downloaded but dividends occur on average less than monthly), making it unwieldy when requesting prices over, say, decades.

My feature request (for working around this bug) is as follows.  Please add a method to allow querying historical _dividend_ data (daily) that does not also (internally) download daily price data.  (Or is there already some method to do this?  I couldn't find one.)  Thanks.

**Comment by JECSand** [comment]
nealeyoung,

Thank you for bringing this to my attention. No, there is not a method in yahoofinancials to get daily dividend data without bringing in the pricing data.

I'll make a new method with functionality to scrape dividend data from web pages such as this one:
https://finance.yahoo.com/quote/AAPL/history?period1=1516996228&period2=1548532228&interval=div%7Csplit&filter=div&frequency=1d

 I can work on this tomorrow and try to get the feature out by tomorrow night.

**Comment by nealeyoung** [comment]
Thanks!

**Comment by JECSand** [comment]
nealeyoung,

I just release v1.5 on pypi with a new method called "get_daily_dividend_data(start_date, end_date)" as requested. I've documented an example for it in the v1.5 readme.rst.  Let me know if this works for you.

Thanks!

**Comment by nealeyoung** [comment]
Will do, thanks!  May take me some weeks.
