### ISSUE TITLE
ETF's stopped working

### ISSUE THREAD

**Issue by sylvandb** [JECSand/yahoofinancials#21]
VXUS and VTI do not retrieve, and are reported failing with a 502.

edit: They worked on Friday. Also fails for mutual funds such as VIIIX

Attempting the same URL using 'curl' from the commandline gets a 302 redirect, and following that redirect returns the data.

and FYI, the retries are excessive. It takes a very, very long time. I put a commit on the top of my master branch that seems to help by differentiating on and caching the failure. (You can take it if you are interested, but I'm not ready to do a PR yet for it.)

**Comment by sylvandb** [comment]
It appears to be related to an http and https proxy. Specifically, python urllib misusing the proxy, sending 'GET https://finance.yahoo.com/...' instead of 'CONNECT finance.yahoo.com'

**Comment by JECSand** [comment]
Hi sylvandb,

As always thank you for all of your help and letting me know about this slowdown. I'll have some time this weekend to take a look into the 302 redirect and the inefficient retires. If you have any code you want to merge let me know as well!

Thanks!
