### ISSUE TITLE
It slowed down a bit recently

### ISSUE THREAD

**Issue by hellojinwoo** [JECSand/yahoofinancials#22]
It used to be much faster to crawl data such as historical daily prices but recently, it slowed down a bit.

```
For ticker in ticker_list :  # ticker_list has 445 tickers in total
    yahoo_financials = YahooFinancials(ticker)
    historical_data = yahoo_financials.get_historical_price_data('2019-02-01','2019-02-25, 'daily')
```
For example, the code above took me about 20 minutes to complete.
Why did it slow down so much and can you handle this issue please?

**Comment by sylvandb** [comment]
which version was okay and which version did the slow down happen?

if you didn't change version, the problem is not this code.

**Comment by hellojinwoo** [comment]
I am using the most recent version, v1.5 and it seems that it slowed down after I installed the version v1.5.

**Comment by JECSand** [comment]
Hi hellojinwoo,

I will do some benchmarking between v1.4 and v1.5 over the coming weekend and get back to you about this. Thank you for bringing this to our attention!

**Comment by hellojinwoo** [comment]
Now it got about 2 times faster than before! I don't know why but I will close this issue :D
