### ISSUE TITLE
Way to get more than 4 years or 4 quarters of financial data

### ISSUE THREAD

**Issue by thezoug** [JECSand/yahoofinancials#29]
Is there an existing parameter to specify how many periods of financial statements to pull? I would like to pull more than the default 4 years or quarters. If not, hopefully we can add that

**Comment by LeeZeitz** [comment]
I think this is a limitation of Yahoo finance itself, and not of this (wonderful) package. They only provide financials for 4 of whichever time interval you select (annual or quarterly). I think to get anything dating further back you'll have to dig around on the respective company websites (not super easy to automate unfortunately)

**Comment by JECSand** [comment]
@thezoug 

Unfortunately as far as I can tell this is a limitation of Yahoo Finance itself. I'd advise creating a database and storing the data for future use if needed. This is something I have attempted to get around in the past to no avail.
