### ISSUE TITLE
Returned JSON difficult to parse 

### ISSUE THREAD

**Issue by analystguy** [JECSand/yahoofinancials#36]
First  - thanks for the great tools. I am rather new to Python and am having difficulty parsing the returned json into a dataframe. Is there a plan in the works to do so or can anyone offer assistance?
The json returned appears as one long unstructured dictionary string.

**Comment by sylvandb** [comment]
Isn't the returned data a dict or maybe a list of dict?
if you print(value) it will convert whatever it is into a string

you can experiment interactively with python, and try `type(value)`

alternatively, if somehow you do have a string containing json data then:
```
import json
value = json.loads(string_value)
```

**Comment by sabirjana** [comment]
Hello, great work!! Is there an easy way to get data in pandas dataframe from various supported methods ?
Thanks

**Comment by JECSand** [comment]
Hi Analyst guy,
