### ISSUE TITLE
get_financial_stmts() returning none

### ISSUE THREAD

**Issue by coolmaddy85** [JECSand/yahoofinancials#59]
Today when I tried get_financial_stmts(), it's returning none. 

Please note everything was working fine till a week back.

I'm in the middle of a project, It'll be really great if it's fixed at the earliest.

Thank you

**Comment by almalh** [comment]
I have the same issue, it looks like it can't fetch the data anymore

**Comment by promsieho** [comment]
plz help ! same issue here 
Thanks!

**Comment by galanCA** [comment]
I have the same problem as the users above. I've being running my code for 6 month with no problems. My guess is that the issue is related to Yahoo's new interface.

Any help is greatly appreciated.

Thank you

**Comment by galanCA** [comment]
I found this web api that achieves the same goal. https://financialmodelingprep.com/developer/docs/

**Comment by tioneb22** [comment]
@galanCA Thanks, very helpful. It's too bad it doesn't provide the float like yahoo does :(

**Comment by juanmf** [comment]
Same here:
```python
        DataStore(yahooFinancials.get_key_statistics_data(),  // works
                                   yahooFinancials.get_historical_price_data(startDate, today, "daily"),   // works
                                   yahooFinancials.get_financial_stmts('annual', 'balance'),   // empty {}
                                   yahooFinancials.get_financial_stmts('annual', 'income'), // empty {}
                                   yahooFinancials.get_financial_stmts('quarterly', 'cash'), // empty {}
                                   yahooFinancials.get_summary_data()) // empty {}
```

Is there any plan to fix this?
