### ISSUE TITLE
Assertion Errors when running the test py

### ISSUE THREAD

**Issue by ipccheng** [JECSand/yahoofinancials#64]
$ python test_yahoofinancials.py 
.FFF
======================================================================
FAIL: test_yf_fundamentals (__main__.TestModule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_yahoofinancials.py", line 68, in test_yf_fundamentals
    self.assertEqual(result, True)
AssertionError: False != True

======================================================================
FAIL: test_yf_historical_price (__main__.TestModule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_yahoofinancials.py", line 88, in test_yf_historical_price
    self.assertDictEqual(single_stock_prices['C']['prices'][0], expect_dict)
AssertionError: {'high': 49.099998474121094, 'volume': 125737200, 'formatted_date': '2015-01-12' [truncated]... != {'high': 49.099998474121094, 'volume': 125737200, 'low': 46.599998474121094, 'cl [truncated]...
- {'adjclose': 43.8124885559082,
+ {'adjclose': 45.35684585571289,
   'close': 47.61000061035156,
   'date': 1421038800,
   'formatted_date': '2015-01-12',
   'high': 49.099998474121094,
   'low': 46.599998474121094,
   'open': 48.959999084472656,
   'volume': 125737200}
======================================================================
FAIL: test_yf_module_methods (__main__.TestModule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_yahoofinancials.py", line 108, in test_yf_module_methods
    self.assertEqual(False, True)
AssertionError: False != True
----------------------------------------------------------------------
Ran 4 tests in 121.016s
FAILED (failures=3)

**Comment by mnatz** [comment]
I have the same error. Any progress on solving this issue?
