### ISSUE TITLE
deprecated?

### ISSUE THREAD

**Issue by a3igner** [JECSand/yahoofinancials#65]
this doesnt work anymore.

**Comment by eleow** [comment]
Just tried and downloading of daily ticker data is working. What is specifically not working for you?

**Comment by a3igner** [comment]
did you try  ES=F ?


Dr Andreas A Aigner
http://www.tradeflags.com
WhatsApp +43 664 5177 139
Skype Aigner_Andreas

**Comment by eleow** [comment]
![image](https://user-images.githubusercontent.com/4363234/78545455-6534a880-782e-11ea-9a23-96b3b4375805.png)
Just tried with "ES=F", freq="daily", no issue. Maybe your syntax is wrong. 

```python
from yahoofinancials import YahooFinancials 

freq = 'daily'
ticker = 'ES=F'
start_date = '2015-01-05'
end_date = '2020-04-12'
yahoo_financials = YahooFinancials(ticker)
df = yahoo_financials.get_historical_price_data(start_date, end_date, freq)
# df.to_csv(path, header=True, index=True)
```

**Comment by a3igner** [comment]
thanks.

i mean the live price / current price can you grab it?

**Comment by antoscha** [comment]
No way. Live market data have its price, it's a common rule and exchanges' requirement. 30-min delayed quotes is the best you can hope to get for free.

**Comment by a3igner** [comment]
I mean the Last price like shown on yahoo. Without grabbing the history. I know it’s delayed.

**Comment by juanpatriciopdlc** [comment]
I am having problems running the code as I get this message:

> \anaconda3\lib\site-packages\yahoofinancials\__init__.py:140: DeprecationWarning: UrlOpener style of invoking requests is deprecated. Use newer urlopen functions/methods
>   urlopener = UrlOpener()

Is anyone getting the same output? Is there anyway to solve this?

**Comment by JECSand** [comment]
I’ll be more active in maintaining YF. No intention of deprecating.
