### ISSUE TITLE
Unknown error - AttributeError: 'NoneType' object has no attribute 'group

### ISSUE THREAD

**Issue by ryantobin77** [JECSand/yahoofinancials#71]
I just installed this with:
$ pip install yahoofinancials

I added a very simple script:
from yahoofinancials import YahooFinancials
yahoo_financials = YahooFinancials('AAPL')
print(yahoo_financials.get_market_cap())

And I got the following error:
  File "Main.py", line 9, in parse
    print(yahoo_financials.get_market_cap())
  File "/Library/Python/2.7/site-packages/yahoofinancials/__init__.py", line 737, in get_market_cap
    return self._stock_price_data('marketCap')
  File "/Library/Python/2.7/site-packages/yahoofinancials/__init__.py", line 649, in _stock_price_data
    if self.get_stock_price_data()[self.ticker] is None:
  File "/Library/Python/2.7/site-packages/yahoofinancials/__init__.py", line 603, in get_stock_price_data
    return self.get_clean_data(self.get_stock_tech_data('price'), 'price')
  File "/Library/Python/2.7/site-packages/yahoofinancials/__init__.py", line 491, in get_stock_tech_data
    return self.get_stock_data(tech_type=tech_type)
  File "/Library/Python/2.7/site-packages/yahoofinancials/__init__.py", line 473, in get_stock_data
    dict_ent = self._create_dict_ent(self.ticker, statement_type, tech_type, report_name, hist_obj)
  File "/Library/Python/2.7/site-packages/yahoofinancials/__init__.py", line 406, in _create_dict_ent
    re_data = self._scrape_data(YAHOO_URL, tech_type, statement_type)
  File "/Library/Python/2.7/site-packages/yahoofinancials/__init__.py", line 153, in _scrape_data
    self._cache[url] = loads(re.search("root.App.main\s+=\s+(\{.*\})", script).group(1))
AttributeError: 'NoneType' object has no attribute 'group

**Comment by sylvandb** [comment]
New version of beautiful soup did a backwards incompatible change.

```
                     script = re_script.text
+                    # bs4 4.9.0 changed so text from scripts is no longer considered text
+                    if not script:
+                        script = re_script.string
                     self._cache[url] = loads(re.search("root.App.main\s+=\s+(\{.*\})", script).group(1))
```

**Comment by jb920** [comment]
still seeing the same issue after installing beautifulsoup4 4.8.0

my code is this: 
ticker = 'AAPL'
yahoo_financials = YahooFinancials(ticker)

balance_sheet_data_qt = yahoo_financials.get_financial_stmts('quarterly', 'balance')

**Comment by preisleistung** [comment]
Same problem here. Beautifulsoup 4.7.0 does not return any error but it returns a `print(yahoo_financials.get_market_cap())` returns None

**Comment by sylvandb** [comment]
seems the 'financials' info problem goes deeper, to a yahoo change restricting that info.

**Comment by juanpatriciopdlc** [comment]
After the fixing @sylvandb has done that you can see on the pull request, **I confirm that the code works perfectly fine.**

I have jusr run:
`from yahoofinancials import YahooFinancials
yahoo_financials = YahooFinancials('AAPL')
print(yahoo_financials.get_market_cap())`

And get:
`1239004610560`

And after:

`balance_sheet_data_qt = yahoo_financials.get_financial_stmts('quarterly', 'balance')
print(balance_sheet_data_qt`

The output is:

`{'balanceSheetHistoryQuarterly': {'AAPL': [{'2019-12-28': {'totalLiab': 251087000000,
     'totalStockholderEquity': 89531000000,
     'otherCurrentLiab': 40577000000,
     'totalAssets': 340618000000,
     'commonStock': 45972000000,
     'otherCurrentAssets': 12026000000,
     'retainedEarnings': 43977000000,
     'otherLiab': 48648000000,
     'treasuryStock': -418000000,
     'otherAssets': 33195000000,
     'cash': 39771000000,
     'totalCurrentLiabilities': 102161000000,
     'shortLongTermDebt': 10224000000,
     'otherStockholderEquity': -418000000,
     'propertyPlantEquipment': 44293000000,
     'totalCurrentAssets': 163231000000,
     'longTermInvestments': 99899000000,
     'netTangibleAssets': 89531000000,
     'shortTermInvestments': 67391000000,
     'netReceivables': 39946000000,
     'longTermDebt': 93078000000,
     'inventory': 4097000000,
     'accountsPayable': 45111000000}},
   {'2019-09-28': {'totalLiab': 248028000000,
     'totalStockholderEquity': 90488000000,
     'otherCurrentLiab': 43242000000,
     'totalAssets': 338516000000,
     'commonStock': 45174000000,
     'otherCurrentAssets': 12352000000,
     'retainedEarnings': 45898000000,
     'otherLiab': 50503000000,
     'treasuryStock': -584000000,
     'otherAssets': 32978000000,
     'cash': 48844000000,
     'totalCurrentLiabilities': 105718000000,
     'shortLongTermDebt': 10260000000,
     'otherStockholderEquity': -584000000,
     'propertyPlantEquipment': 37378000000,
     'totalCurrentAssets': 162819000000,
     'longTermInvestments': 105341000000,
     'netTangibleAssets': 90488000000,
     'shortTermInvestments': 51713000000,
     'netReceivables': 45804000000,
     'longTermDebt': 91807000000,
     'inventory': 4106000000,
     'accountsPayable': 46236000000}},
   {'2019-06-29': {'totalLiab': 225783000000,
     'totalStockholderEquity': 96456000000,
     'otherCurrentLiab': 37107000000,
     'totalAssets': 322239000000,
     'commonStock': 43371000000,
     'otherCurrentAssets': 10530000000,
     'retainedEarnings': 53724000000,
     'otherLiab': 51143000000,
     'treasuryStock': -639000000,
     'otherAssets': 33634000000,
     'cash': 50530000000,
     'totalCurrentLiabilities': 89704000000,
     'shortLongTermDebt': 13529000000,
     'otherStockholderEquity': -639000000,
     'propertyPlantEquipment': 37636000000,
     'totalCurrentAssets': 134973000000,
     'longTermInvestments': 115996000000,
     'netTangibleAssets': 96456000000,
     'shortTermInvestments': 44084000000,
     'netReceivables': 26474000000,
     'longTermDebt': 84936000000,
     'inventory': 3355000000,
     'accountsPayable': 29115000000}},
   {'2019-03-30': {'totalLiab': 236138000000,
     'totalStockholderEquity': 105860000000,
     'otherCurrentLiab': 40900000000,
     'totalAssets': 341998000000,
     'commonStock': 42801000000,
     'otherCurrentAssets': 12092000000,
     'retainedEarnings': 64558000000,
     'otherLiab': 52165000000,
     'treasuryStock': -1499000000,
     'otherAssets': 34587000000,
     'cash': 37988000000,
     'totalCurrentLiabilities': 93772000000,
     'shortLongTermDebt': 10505000000,
     'otherStockholderEquity': -1499000000,
     'propertyPlantEquipment': 38746000000,
     'totalCurrentAssets': 123346000000,
     'longTermInvestments': 145319000000,
     'netTangibleAssets': 105860000000,
     'shortTermInvestments': 42104000000,
     'netReceivables': 26278000000,
     'longTermDebt': 90201000000,
     'inventory': 4884000000,
     'accountsPayable': 30443000000}}]}}`

**Comment by dalder1** [comment]
I am still getting errors when trying to use get_current_price... should I downgrade bs4 or what?

**Comment by juanpatriciopdlc** [comment]
It works for me without downgrading. Just try to do what @sylvandb says in this pull:
https://github.com/JECSand/yahoofinancials/pull/72/files

I did it and everything is ok

**Comment by dalder1** [comment]
Okay thank you. I replaced the init.py in my library with @sylvandb file by simply copying and pasting; it now works. 

I am pretty new to github/python in general (I’m a cs student with a c/c++ background), in the future is there a better way to update my library with a forked version?

**Comment by HyperionSounds** [comment]
I am also having this issue, I will try the fix above.

**Comment by trenton3983** [comment]
> It works for me without downgrading. Just try to do what @sylvandb says in this pull:
> https://github.com/JECSand/yahoofinancials/pull/72/files
> 
> I did it and everything is ok

I was also having the same issue and this resolved it.

**Comment by HyperionSounds** [comment]
> > It works for me without downgrading. Just try to do what @sylvandb says in this pull:
> > https://github.com/JECSand/yahoofinancials/pull/72/files
> > I did it and everything is ok
> 
> I was also having the same issue and this resolved it.

thanks - I am having trouble finding these files, I am in a python3.6.6 virtualenv; what version are you using / where are the files? I tried inside of the site-packages in the virtualenv

**Comment by HyperionSounds** [comment]
Ok I did the above for pull 72 and it worked. Thanks

**Comment by Jigg97** [comment]
Still having no luck with this.

I tried copying and pasting @sylvandb version of the init.py, which still returns the same 'None' error. Haven't done anything with the test file though. Any advice?

Apologies - I am new to all of this!

**Comment by juanmf** [comment]
+1 here:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-2-aeb26be1001e> in <module>
     17 yahoo_financials_treasuries = YahooFinancials(us_treasuries)
     18 
---> 19 tech_cash_flow_data_an = yahoo_financials_tech.get_financial_stmts('annual', 'cash')
     20 
     21 print(tech_cash_flow_data_an)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yahoofinancials/__init__.py in get_financial_stmts(self, frequency, statement_type, reformat)
    590         report_num = self.get_report_type(frequency)
    591         if isinstance(statement_type, str):
--> 592             data = self._run_financial_stmt(statement_type, report_num, reformat)
    593         else:
    594             data = {}

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yahoofinancials/__init__.py in _run_financial_stmt(self, statement_type, report_num, reformat)
    580         report_name = self.YAHOO_FINANCIAL_TYPES[statement_type][report_num]
    581         if reformat:
--> 582             raw_data = self.get_stock_data(statement_type, report_name=report_name)
    583             data = self.get_reformatted_stmt_data(raw_data, statement_type)
    584         else:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yahoofinancials/__init__.py in get_stock_data(self, statement_type, tech_type, report_name, hist_obj)
    476             for tick in self.ticker:
    477                 try:
--> 478                     dict_ent = self._create_dict_ent(tick, statement_type, tech_type, report_name, hist_obj)
    479                     data.update(dict_ent)
    480                 except ManagedException:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yahoofinancials/__init__.py in _create_dict_ent(self, up_ticker, statement_type, tech_type, report_name, hist_obj)
    397         if tech_type == '' and statement_type != 'history':
    398             try:
--> 399                 re_data = self._scrape_data(YAHOO_URL, tech_type, statement_type)
    400                 dict_ent = {up_ticker: re_data[u'' + report_name], 'dataType': report_name}
    401             except KeyError:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yahoofinancials/__init__.py in _scrape_data(self, url, tech_type, statement_type)
    151                     if re_script is not None:
    152                         script = re_script.text
--> 153                         self._cache[url] = loads(re.search("root.App.main\s+=\s+(\{.*\})", script).group(1))
    154                         response.close()
    155                         break

AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by yzhou2000** [comment]
I replaced the init.py in my library with @sylvandb file by simply copying and pasting; it now works.
