### ISSUE TITLE
get_financial_stmts returns nothing

### ISSUE THREAD

**Issue by eyalk5** [JECSand/yahoofinancials#73]
from yahoofinancials import YahooFinancials as YF
tick = YF('MSFT')
tick.get_financial_stmts('quarterly', 'balance')

In[8]: tick.get_financial_stmts('quarterly', 'balance')
Out[8]: {'balanceSheetHistoryQuarterly': {'MSFT': None}}

**Comment by bluusun** [comment]
Same issue on Mac OSX, python3.7. Installation via pip3.

**Comment by eyalk5** [comment]
See solution here https://github.com/ranaroussi/yfinance/issues/291

**Comment by dalder1** [comment]
@eyalk5 could you explain how to implement this change for yahoofinancials. I do not see a base.py from yahoofinancials, where should I make the recommended changes.

**Comment by madis** [comment]
I patched it like this:
You'll have to change the location of your yfinance module folder:
```
patch ~/anaconda3/envs/panthera/lib/python3.7/site-packages/yfinance/base.py < patches/yfinance_base.patch
```
The below code is stored in `patches/yfinance_base.patch`
```patch
--- a/yfinance/base.py
+++ b/yfinance/base.py
@@ -280,8 +280,8 @@ class TickerBase():
         data = utils.get_json(url, proxy)

         # holders
-        url = "{}/{}/holders".format(self._scrape_url, self.ticker)
-        holders = _pd.read_html(url)
+        urlH = "{}/{}/holders".format(self._scrape_url, self.ticker)
+        holders = _pd.read_html(urlH)
         self._major_holders = holders[0]
         self._institutional_holders = holders[1]
         if 'Date Reported' in self._institutional_holder
```

**Comment by dalder1** [comment]
Okay I understand what you did, but I’m still not sure how to make this work for yahoofinancials. There’s no base.py or yfinance library in my yahoofinancials directory.

**Comment by sylvandb** [comment]
I don't understand how or why renaming a variable (url to urlH) would fix this issue with the yahoo pages. Perhaps a different patch was significant?
