### ISSUE TITLE
Get_financial_stmts still return None

### ISSUE THREAD

**Issue by syrakusmrdrte** [JECSand/yahoofinancials#75]
I have tried and tried to search for solutions, but 
ticker="AAPL"
YahooFinancials(ticker).get_financial_stmts("annual",["income","cash","balance"]) 
returns 
{'incomeStatementHistory': {'AAPL':None},
'cashflowStatementHistory':{'AAPL':None},
'balanceSheetHistory':{'AAPL':None}}

Is there any way to solve this so that I get the financial statements?

**Comment by CDCDM1986** [comment]
I have got the same issue. Anyone has any insight?

**Comment by biggestT** [comment]
Also had the same issue after adding [the BeautifulSoup fix](https://github.com/JECSand/yahoofinancials/pull/72/files#diff-859f0dd652dec0f5114399943a987467R153-R155), that I got these `None` results.

@syrakusmrdrte, @CDCDM1986 I Fixed it by adding [the second user-agent header change fix](https://github.com/JECSand/yahoofinancials/pull/72/files#diff-859f0dd652dec0f5114399943a987467L71-R71). Perhaps Yahoo is blocking the previous one, but seems like they at least respond HTTP 200 so not sure.

**Comment by Wenseslaus** [comment]
Hey biggestT. I did quite understand your solution.

**Comment by avelaga** [comment]
wow @biggestT thank you that fixed it!!

**Comment by Frodriguez9** [comment]
> wow @biggestT thank you that fixed it!!

Can you tell me what did you do?

**Comment by Frodriguez9** [comment]
> Also had the same issue after adding [the BeautifulSoup fix](https://github.com/JECSand/yahoofinancials/pull/72/files#diff-859f0dd652dec0f5114399943a987467R153-R155), that I got these `None` results.
> 
> @syrakusmrdrte, @CDCDM1986 I Fixed it by adding [the second user-agent header change fix](https://github.com/JECSand/yahoofinancials/pull/72/files#diff-859f0dd652dec0f5114399943a987467L71-R71). Perhaps Yahoo is blocking the previous one, but seems like they at least respond HTTP 200 so not sure.

I'm sorry, I am a beginner  programer. I am not sure what to do with that information, can you tell me how to actually apply your solution?

My biggest appreciation in advance!

**Comment by avelaga** [comment]
@Frodriguez9 i made the edits in the yahoofinancials/__init__.py that was linked to. here's the fully fixed file that works for me - https://gist.github.com/avelaga/762142a778c2e3a969fbb78ec351d6e8

you want to replace <python-path>/yahoofinancials/__init__.py with this fixed __init__.py file.
if you can't find the package, do:
```
python3
import sys
print(sys.path)
exit()
```
to find the python path and search through those to find yahoofinancials

in aws: /usr/local/lib/python3.7/site-packages/yahoofinancials
in raspian: /home/pi/.local/lib/python3.7/site-packages/yahoofinancials
in macos: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yahoofinancials

hope that helps!

**Comment by Frodriguez9** [comment]
@avelaga thank you so much! it worked!.

I was telling a friend that one of the things I've enjoyed the most since I started to become involved with IT was to find such helpful community of programers. You guys are always willing to assist others. 

No wonder why IT keeps evolving more rapidly than all other industries combined. Thank you so much!

**Comment by avelaga** [comment]
@Frodriguez9 awesome!! yeah the online community is amazing, i've gotten a ton of help myself on reddit especially. its an amazing field and really rewarding to share it with others. im glad i could help :)

**Comment by wwang184** [comment]
@biggestT That solution works for me too! Many thanks!
