### ISSUE TITLE
No data returned?

### ISSUE THREAD

**Issue by AnonJohn** [JECSand/yahoofinancials#82]
All data seems to return as None. Example from running demo.py on a fresh git clone, but same thing for other tickers in my own code.
----------------------------------------------------------------

{'MMM': None, 'AAPL': None}
----------------------------------------------------------------
{'MMM': None, 'AAPL': None}
----------------------------------------------------------------
{'MMM': None, 'AAPL': None}
----------------------------------------------------------------
{'MMM': None, 'AAPL': None}
----------------------------------------------------------------
{'MMM': None, 'AAPL': None}
----------------------------------------------------------------
dict_keys(['https://finance.yahoo.com/quote/MMM/financials?p=MMM', 'https://finance.yahoo.com/quote/AAPL/financials?p=AAPL'])
----------------------------------------------------------------
8.928906440734863 seconds

**Comment by nitin-rathi** [comment]
I also have the same issue. Let me know if you are able to solve it

**Comment by AnonJohn** [comment]
Hi - No, I fear I didn't try. Thanks for confirming it though. My needs are simple so I used yfinance instead!

**Comment by segelmache** [comment]
Same Problem :-/

**Comment by promsieho** [comment]
Same

**Comment by hannahrosey** [comment]
Same here

**Comment by AtulVG** [comment]
No data is being returned

**Comment by JECSand** [comment]
I pushed a new version 1.6 with changes from @sylvandb. It appears to be working again. Let me know if this issue persists.
