### ISSUE TITLE
"'NoneType' object has no attribute 'group' " when calling "get_financial_stmts"

### ISSUE THREAD

**Issue by segelmache** [JECSand/yahoofinancials#83]
Hi JECSand,

I tried out your code examples:
```
>> from yahoofinancials import YahooFinancials as yfs
>> ticker = 'AAPL'
>> yahoo_financials = yfs(ticker)
>> balance_sheet_data_qt = yahoo_financials.get_financial_stmts('quarterly', 'balance')`

ERROR: NoneType' object has no attribute 'group' 
```

Is it just me?
Thanks and regards

**Comment by Jacques2101** [comment]
I have the same message...I just can download historical data with : yahoo_financials.get_historical_price_data('2017-09-15', '2018-09-15', 'weekly')

Help needed !

**Comment by giteho** [comment]
@segelmache @Jacques2101 
Your issue sounds like a duplicate of #71. Just try to do what @sylvandb says in this pull:
https://github.com/JECSand/yahoofinancials/pull/72/files

**Comment by xixiakl** [comment]
I am getting the same error too :(.

**Comment by sengwloke** [comment]
> ERROR: NoneType' object has no attribute 'group'

I am getting the same error

**Comment by sengwloke** [comment]
same error
